# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuscaRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuscaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CadastroRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificadorAgendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificadorCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('patrimonio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('000', 'Desconhecido'), ('001', 'Monitor'), ('002', 'Projetor'), ('003', 'Acessório para computador'), ('004', 'Computador'), ('005', 'Material de escritório'), ('006', 'Móvel'), ('007', 'Sala de Aula'), ('008', 'Auditório'), ('009', 'Imóvel'), ('010', 'Equipamento laboratorial'), ('011', 'Equipamento de limpeza'), ('012', 'Equipamento métrico'), ('013', 'Equipamento de manutenção'), ('014', 'Outro equipamento')], default='000', max_length=3)),
            ],
            options={
                'db_table': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('estado', models.PositiveSmallIntegerField()),
                ('tipo_perfil', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
