# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('periodo', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('AG', 'Agendado'), ('CA', 'Cancelado'), ('CF', 'Confirmado')], default='AG', max_length=2)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario')),
            ],
            options={
                'db_table': 'Agendamentos',
            },
        ),
    ]
