# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='categoria',
            field=models.CharField(choices=[('000', 'Desconhecido'), ('001', 'Monitor'), ('002', 'Projetor'), ('003', 'Acessório para computador'), ('004', 'Computador'), ('005', 'Material de escritório'), ('006', 'Móvel'), ('007', 'Sala de Aula'), ('008', 'Auditório'), ('009', 'Imóvel'), ('010', 'Equipamento laboratorial'), ('011', 'Equipamento de limpeza'), ('012', 'Equipamento métrico'), ('013', 'Equipamento de manutenção'), ('014', 'Outro equipamento')], default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='estado',
            field=models.CharField(choices=[('AV', 'Disponível'), ('UV', 'Indisponível'), ('MA', 'Em manutenção')], default='UV', max_length=2),
        ),
    ]
