# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161113_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='estado',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível'), ('Em manutenção', 'Em manutenção')], default='Indisponível', max_length=13),
        ),
    ]
