fakeresources = [
  {
    name: "res1",
    department : "dep1",
    id: 1,
    status: "disponível",
    description: "Alguma descrição do recurso res1",
    category: "A",
  },
  {
    name: "res2",
    department : "dep1",
    id: 2,
    status: "disponível",
    description: "desc",
    category: "A",
  },
  {
    name: "res3",
    department : "dep1",
    id: 3,
    status: "disponível",
    description: "desc",
    category: "A",
  },
  {
    name: "res4",
    department : "dep1",
    id: 4,
    status: "disponível",
    description: "desc",
    category: "B",
  },
  {
    name: "res5",
    department : "dep1",
    id: 5,
    status: "disponível",
    description: "desc",
    category: "B",
  },
  {
    name: "res6",
    department : "dep1",
    id: 6,
    status: "disponível",
    description: "desc",
    category: "C",
  },
  {
    name: "res7",
    department : "dep4",
    id: 7,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res8",
    department : "dep4",
    id: 8,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res9",
    department : "dep4",
    id: 9,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res10",
    department : "dep4",
    id: 10,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res11",
    department : "dep4",
    id: 11,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res12",
    department : "dep4",
    id: 12,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res13",
    department : "dep4",
    id: 13,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res14",
    department : "dep2",
    id: 14,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res15",
    department : "dep3",
    id: 15,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res16",
    department : "dep3",
    id: 16,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res17",
    department : "dep3",
    id: 17,
    status: "disponível",
    description: "desc",
    category: "F",
  },
  {
    name: "res18",
    department : "dep3",
    id: 18,
    status: "disponível",
    description: "desc",
    category: "F",
  },
  {
    name: "res19",
    department : "dep2",
    id: 19,
    status: "indisponível",
    description: "desc",
    category: "F",
  },
  {
    name: "res20",
    department : "dep2",
    id: 20,
    status: "manutenção",
    description: "desc",
    category: "F",
  },
];

filteredfakeresources = fakeresources;
sortedfakeresources = filteredfakeresources;
