resources = [
  {
    name: "res1",
    department : "dep1",
    id: 1,
    status: "disponível",
    description: "desc",
    category: "A",
  },
  {
    name: "res2",
    department : "dep1",
    id: 2,
    status: "disponível",
    description: "desc",
    category: "A",
  },
  {
    name: "res7",
    department : "dep1",
    id: 3,
    status: "disponível",
    description: "desc",
    category: "A",
  },
  {
    name: "res6",
    department : "dep1",
    id: 4,
    status: "disponível",
    description: "desc",
    category: "B",
  },
  {
    name: "res5",
    department : "dep1",
    id: 5,
    status: "disponível",
    description: "desc",
    category: "B",
  },
  {
    name: "res4",
    department : "dep1",
    id: 6,
    status: "disponível",
    description: "desc",
    category: "C",
  },
  {
    name: "res3",
    department : "dep4",
    id: 7,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res1",
    department : "dep4",
    id: 8,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res1",
    department : "dep4",
    id: 9,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res1",
    department : "dep4",
    id: 10,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res1",
    department : "dep4",
    id: 11,
    status: "disponível",
    description: "desc",
    category: "D",
  },
  {
    name: "res1",
    department : "dep4",
    id: 12,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res1",
    department : "dep4",
    id: 13,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res1",
    department : "dep2",
    id: 14,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res1",
    department : "dep3",
    id: 15,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res1",
    department : "dep3",
    id: 16,
    status: "disponível",
    description: "desc",
    category: "E",
  },
  {
    name: "res1",
    department : "dep3",
    id: 17,
    status: "disponível",
    description: "desc",
    category: "F",
  },
  {
    name: "res1",
    department : "dep3",
    id: 18,
    status: "disponível",
    description: "desc",
    category: "F",
  },
  {
    name: "res1",
    department : "dep2",
    id: 19,
    status: "disponível",
    description: "desc",
    category: "F",
  },
  {
    name: "res1",
    department : "dep2",
    id: 20,
    status: "disponível",
    description: "desc",
    category: "F",
  },

]
